java_test(
    name = "vs_code_bazel_tests",
    srcs = ["EmployeeTest.java"],
    test_class = "com.xyzcorp.EmployeeTest",
    deps = [
        "@maven//:junit_junit",
        "@maven//:org_assertj_assertj_core",
    ]
)